const AMOUNT_RANDOM_PHOTOS = 10;
const RERENDER_DELAY = 500;
const AMOUNT_UPLOAD_COMMENTS = 5;
const SCALE_STEP = 25;
const SCALE_MIN = 25;
const SCALE_MAX = 100;
const DELAY_ALERT_MESSAGE = 5000;
const AMOUNT_HASHTAGS = 5;
const COMMENT_LENGTH = 140;

export {AMOUNT_RANDOM_PHOTOS, RERENDER_DELAY, AMOUNT_UPLOAD_COMMENTS, SCALE_STEP, SCALE_MIN, SCALE_MAX, DELAY_ALERT_MESSAGE, AMOUNT_HASHTAGS, COMMENT_LENGTH};
